;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-semi&comma
        dabbrev-expand
        end-of-visual-line
        indent-for-tab-command
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-edit-src-save
        org-self-insert-command
        org-yank
        sgml-slash
        smex
        sp--self-insert-command
        sp-forward-slurp-sexp
        td/join-next-line
        td/kill-region-or-word
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        select-window-0
        undo-tree-visualizer-quit
        ))
